---
  - hosts: default
    become: true

    tasks:
      - name: update the apt-get
        apt:
          update_cache: yes
      
      - name: Add an Apt signing key to a specific keyring file
        apt_key:
          url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
          keyring: /usr/share/keyrings/elasticsearch-keyring.gpg
          state: present

      - name: Install transport
        apt:
          name: "apt-transport-https"
          state: present

      - name: Adding Elastic APT repository
        apt_repository:
          repo: deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main
          state: present
          filename: elastic-8.x.list
          update_cache: yes

      - name: install elasticsearch
        apt:
          name: elasticsearch
          state: present
          update_cache: yes

#       - name: Updating the config file to allow outside access
#         lineinfile:
#           destfile: /etc/elasticsearch/elasticsearch.yml
#           regexp: 'network.host:'
#           line: 'network.host: "0.0.0.0"'
      
# # Update Elasticsearch port in config file 

#       - name: Updating the port in config file 
#         lineinfile:
#           destfile: /etc/elasticsearch/elasticsearch.yml
#           regexp: 'http.port:'
#           line: 'http.port: 9200'

      - name: Enabling elastic search service
        systemd:
          name: elasticsearch
          enabled: yes
          daemon_reload: yes
# Start Kibana service
      - name: Starting elastic search service
        systemd:
          name: elasticsearch
          state: started
          
      - name: Ensure elastic serach is running
        systemd: state=started name=elasticsearch