---
  - hosts: default
    become: true

    tasks:
      - name: update the apt-get
        apt:
          update_cache: yes

      - name: Add an Apt signing key to a specific keyring file
        apt_key:
          url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
          state: present
          
      - name: Install transport
        apt:
          name: apt-transport-https
          state: present

      - name: Adding APT repository
        apt_repository:
          repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
          state: present
          filename: elastic-7.x.list
          update_cache: yes
      - name: Update repositories cache and install Kibana
        apt:
          name: kibana
          update_cache: yes
# Configure kibana.yml
      # - name: Updating the config file to allow outside access
      #   lineinfile:
      #     destfile: /etc/kibana/kibana.yml
      #     regexp: 'server.host:'
      #     line: 'server.host: 0.0.0.0'

      # - name: Defining server port
      #   lineinfile:
      #     destfile: /etc/kibana/kibana.yml
      #     regexp: 'server.port:'
      #     line: 'server.port: 5601'
    
      # - name: Defining Elasticsearch URL
      #   lineinfile:
      #     destfile: /etc/kibana/kibana.yml
      #     regexp: 'elasticsearch.url:'
      #     line: 'elasticsearch.url: "http://localhost:9200"'
   
# Enable Kibana service
      - name: Enabling Kibana service
        systemd:
          name: kibana
          enabled: yes
          daemon_reload: yes
# Start Kibana service
      - name: Starting Kibana service
        systemd:
          name: kibana
          state: started
      - name: Ensure Kibana is running
        systemd: state=started name=kibana

